---
ansible_atomic_red_team_common_install_packages:
  - wget
  - realmd
  - sssd
  - python3-pexpect
  - python3-pip

ansible_atomic_red_team_debian_specific_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - libunwind8
  - software-properties-common
  - libpam-sss
  - libnss-sss
  - python3-full

ansible_atomic_red_team_redhat_specific_packages:
  - libicu
  - unzip
  - tar
  - oddjob
  - oddjob-mkhomedir
  - samba-common-tools
