---
dependencies: []

galaxy_info:
  role_name: ludus_rearm_windows
  author: dotknewt
  description: An Ansible Role that rearms eval lisences on Windows >= 10 hosts
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - "2012"
        - "2019"
        - "2022"
        - "2025"
  galaxy_tags:
    - license
collections:
  - community.windows
