---
- name: Copy Sysmon executable to SystemRoot
  ansible.windows.win_copy:
    remote_src: true
    src: '{{ sysmon_dl_temp.path }}\Sysmon64.exe'
    dest: "{{ sysmon_executable_path }}"

- name: Install Sysmon
  ansible.windows.win_command:
    cmd: >-
      "{{ sysmon_executable_path }}"
      {{ sysmon_install_default_parameters | join(" ") }}
  register: sysmon_install
  changed_when: sysmon_install.rc == 0
