- name: Update packages
  ansible.builtin.apt:
    update_cache: true

- name: Install Dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add an Apt signing key
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install Docker Packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Download Minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    dest: /tmp/minikube_latest_amd64.deb
    mode: "0644"
    validate_certs: false

- name: Install Minikube
  ansible.builtin.apt:
    deb: /tmp/minikube_latest_amd64.deb

- name: Create Docker Group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user 'debian' to primary group of 'docker'
  ansible.builtin.user:
    name: debian
    comment: Debian User
    uid: 1000
    group: docker

- name: Get latest kubectl version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: kubectl_version

- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: "0755"

- name: Download and install Helm
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    creates: /usr/local/bin/helm

- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
